# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 604d9ffd37f6c67644ee1ffbd3324b427e1d74006cde4c0c0316d65098fcbc389ccfacb18ac0ae6ce8765674bb0bfad66dfc878b8d4218134d31a5f8ce653198

test:
  secret_key_base: 486445190cb38219d9191bdcfc549627848e69627d157ac97dd39a1785928fe053cbd46e57b3f38a26c994190ae1af690df3bc558fafb4ca2dc2410e2ff36fa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
